FROM node:16-alpine

# 创建工作目录
WORKDIR /app

# 复制package.json和package-lock.json
COPY package*.json ./

# 安装依赖
RUN npm install --production

# 复制应用代码
COPY . .

# 创建上传目录
RUN mkdir -p uploads && chmod -R 755 uploads

# 暴露端口
EXPOSE 5000

# 启动应用
CMD ["npm", "start"]