version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: download-web-backend
    restart: always
    environment:
      NODE_ENV: production
      PORT: 5000
      JWT_SECRET: your_random_secure_jwt_secret_key
      JWT_EXPIRE: 30d
      UPLOAD_PATH: uploads
      STORAGE_TYPE: file
    volumes:
      - uploads_data:/app/uploads
      - data_storage:/app/data
    ports:
      - "5000:5000"
    networks:
      - download-web-network

  # 前端服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: download-web-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - download-web-network

# 定义网络
networks:
  download-web-network:
    driver: bridge

# 定义数据卷
volumes:
  mysql_data:
  uploads_data: