version: '3.8'

services:
  # MySQL数据库服务
  mysql:
    image: mysql:8.0
    container_name: download-web-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: download_web
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_secure_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - download-web-network
    command: --default-authentication-plugin=mysql_native_password

  # 后端服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: download-web-backend
    restart: always
    depends_on:
      - mysql
    environment:
      NODE_ENV: production
      PORT: 5000
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: download_web
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_secure_password
      JWT_SECRET: your_random_secure_jwt_secret_key
      JWT_EXPIRE: 30d
      UPLOAD_PATH: uploads
    volumes:
      - uploads_data:/app/uploads
    ports:
      - "5000:5000"
    networks:
      - download-web-network

  # 前端服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: download-web-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - download-web-network

# 定义网络
networks:
  download-web-network:
    driver: bridge

# 定义数据卷
volumes:
  mysql_data:
  uploads_data: